spring:
  profiles:
    active: dev
  application:
    name: sweetie
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.8.205:3306/sweetie?useUnicode=true&characterEncoding=utf8
    username: caocao
    password: caocao123
  jooq:
    sql-dialect: mysql_5_7
  thymeleaf:
    mode: HTML
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8082

logging:
  file: ${spring.application.name}
  config: classpath:logback-spring.xml




